apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplewebapp-deployment
  labels:
    app: simplewebapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simplewebapp
  template:
    metadata:
      labels:
        app: simplewebapp
    spec:
      containers:
      - name: simplewebapp
        image: ramkumarpudi.jfrog.io/simplewebapp/task:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred
